---
deployment:
  tasks:
    - export DEPLOYPATH=/home/timpano1/public_html/ptable
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp .last_build_id $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp flutter_service_worker.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp main.dart.js $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp version.json $DEPLOYPATH